version: 2

jobs:
  unit_test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            # create venv
            python3 -m venv /tmp/.venv
            source /tmp/.venv/bin/activate

            # install dependencies
            make update-shared-lib
            primehub_sha=$(make get-primehub-sha)
            z2jh_sha=$(curl -s "https://api.github.com/repos/infuseai/primehub/contents/vendor?ref=${primehub_sha}" | grep -o -e '"sha": "\w\+"' | tr -d '"' | cut -d' ' -f2)
            python -m pip install -U pip
            pip3 install -r https://raw.githubusercontent.com/InfuseAI/zero-to-jupyterhub-k8s/${z2jh_sha}/images/hub/requirements.txt
            pip3 install -r requirements.txt
            pip3 install pytest-cov

            # run tests
            py.test --cov=. --cov-report html

            # upload artifacts
            mkdir -p /tmp/artifacts
            mv htmlcov /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  release_builds:
    jobs:
      - unit_test
